ALTER TABLE users
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'PENDING', 'DEACTIVATED', 'FIRED'));

ALTER TABLE users
    MODIFY COLUMN role ENUM ('CUSTOMER', 'EMPLOYEE', 'MANAGER') NOT NULL;